<?php
$reportTitle = 'Laporan AI Harian';
$title       = $reportTitle . ' - ' . APP_NAME;
?>

<div class="d-flex justify-content-between align-items-center mb-4">
    <div>
        <h1 class="h3 fw-bold text-dark mb-1">
            <i class="fas fa-robot text-primary me-2"></i><?php echo $reportTitle; ?>
        </h1>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb mb-0">
                <li class="breadcrumb-item"><a href="<?php echo BASE_URL; ?>" class="text-decoration-none">Dashboard</a></li>
                <li class="breadcrumb-item">Laporan</li>
                <li class="breadcrumb-item active"><?php echo $reportTitle; ?></li>
            </ol>
        </nav>
    </div>
</div>

<div class="row">
    <div class="col-md-4 mb-4">
        <div class="card border-0 shadow-sm rounded-4 h-100">
            <div class="card-header bg-white border-0 pt-4 pb-0">
                <h5 class="fw-bold"><i class="fas fa-calendar-alt text-secondary me-2"></i>Pilih Tanggal</h5>
            </div>
            <div class="card-body">
                <form method="GET" action="" class="mb-4">
                    <input type="hidden" name="url" value="laporan/ai_summary">
                    <div class="mb-3">
                        <label class="form-label text-muted small fw-bold">Tanggal Aktivitas</label>
                        <input type="date" class="form-control" name="date" value="<?php echo htmlspecialchars($selectedDate); ?>" required>
                    </div>
                    <button type="submit" class="btn btn-outline-primary w-100">Tampilkan Data</button>
                </form>

                <hr>

                <form method="POST" action="">
                    <input type="hidden" name="csrf_token" value="<?php echo SecurityHelper::csrfToken(); ?>">
                    <div class="mb-3">
                        <label class="form-label text-muted small fw-bold">Total Aktivitas Hari Ini</label>
                        <h2 class="fw-bold mb-0 text-primary"><?php echo count($rows); ?></h2>
                        <small class="text-muted">aktivitas tercatat</small>
                    </div>
                    
                    <button type="submit" name="generate_ai" class="btn btn-primary w-100 fw-bold shadow-sm" <?php echo empty($rows) ? 'disabled' : ''; ?>>
                        <i class="fas fa-magic me-2"></i>Generate AI Report
                    </button>
                    <?php if(empty($rows)): ?>
                        <div class="form-text text-danger mt-2 small"><i class="fas fa-info-circle me-1"></i>Tidak ada data untuk di-generate.</div>
                    <?php endif; ?>
                </form>
            </div>
        </div>
    </div>

    <div class="col-md-8 mb-4">
        <div class="card border-0 shadow-sm rounded-4 h-100">
            <div class="card-header bg-white border-0 pt-4 pb-0 d-flex justify-content-between align-items-center">
                <h5 class="fw-bold mb-0">
                    <i class="fas fa-file-alt text-secondary me-2"></i>Hasil Laporan
                </h5>
                <?php if ($aiSummary): ?>
                <span class="badge bg-success-subtle text-success border border-success-subtle rounded-pill px-3 py-2">
                    <i class="fas fa-check-circle me-1"></i>Generated by Gemini AI
                </span>
                <?php endif; ?>
            </div>
            <div class="card-body">
                <?php if ($errorMsg): ?>
                    <div class="alert alert-danger rounded-3 border-0 shadow-sm">
                        <i class="fas fa-exclamation-triangle me-2"></i>
                        <?php echo htmlspecialchars($errorMsg); ?>
                    </div>
                <?php endif; ?>

                <?php if ($aiSummary): ?>
                    <div class="ai-report-content p-4 bg-light rounded-4 border">
                        <?php 
                            // AI summary should be HTML based on our prompt, but we strip dangerous tags just in case
                            echo strip_tags($aiSummary, '<h3><h4><h5><h6><p><ul><ol><li><strong><b><i><em><br>'); 
                        ?>
                    </div>
                    <div class="text-end mt-3">
                        <button class="btn btn-outline-secondary btn-sm" onclick="window.print()">
                            <i class="fas fa-print me-1"></i>Cetak Laporan
                        </button>
                    </div>
                <?php elseif (!$errorMsg): ?>
                    <div class="text-center py-5 text-muted h-100 d-flex flex-column justify-content-center align-items-center">
                        <div class="bg-light rounded-circle p-4 mb-3">
                            <i class="fas fa-robot fs-1 opacity-50 text-primary"></i>
                        </div>
                        <p class="mb-0">Klik tombol <strong>Generate AI Report</strong><br>untuk membuat ringkasan aktivitas.</p>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>

<style>
.ai-report-content h3 { font-size: 1.25rem; font-weight: 700; margin-top: 1rem; margin-bottom: 0.75rem; color: #2c3e50; }
.ai-report-content ul { padding-left: 1.5rem; margin-bottom: 1rem; }
.ai-report-content li { margin-bottom: 0.5rem; }
</style>
